version: '3'
services:
  myservice:
    image: python-rsi
    container_name: py_container
    build: .
    depends_on:
      - db
    #volumes:
    #  - type: volume
    #    source: db-data
    #    target: /app/data
  db:
    image: postgres
    container_name: pg_container
    restart: always
    #environment:
    #  POSTGRES_DB: py-app
    #  POSTGRES_USER: postgres
    #  POSTGRES_PASSWORD: postgres
    env_file:
      - "database.env"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/ 
volumes:
  #db-data:
  pgdata:
